logging:
  console: true
  console_verbosity: DEBUG
  file: false
  file_verbosity: DEBUG
  filename: threatbus.log


plugins:
  backbones:
    inmem:
  apps:
    zeek:
      host: "127.0.0.1"
      port: 47761
      module_namespace: Tenzir
    misp:
      api:
        host: https://localhost
        ssl: false
        key: NpwGjzaWY7sQxovURfOORCFqz7eshxqDWhbARH3E
      zmq:
        host: localhost
        port: 50000
