logging:
  console: false
  file: false

plugins:
  backbones:
    inmem:
  apps:
    zeek:
      host: "0.0.0.0"
      port: 47761
      module_namespace: Tenzir
    zmq_app:
      host: "127.0.0.1"
      manage: 13370
      pub: 13371
      sub: 13372
