logging:
  console: true
  console_verbosity: DEBUG
  file: false
  file_verbosity: DEBUG
  filename: threat-bus.log


plugins:
  backbones:
    inmem:
  apps:
    zeek:
      host: "127.0.0.1"
      port: 47761
