name: "Python Egg"
on: push
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  egg-install:
    name: Egg Installation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Dist Environment
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
    - name: Install Application and Plugins
      run: |
        make clean build
    - name: Package Application and Plugins
      run: |
        make clean dist

  egg-release:
    name: Egg Release
    needs: egg-install
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up Dist Environment
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools twine
    - name: Package Application and Plugins
      run: |
        make clean dist
    - name: Create Release Name
      id: release_name
      run: |
        NAME="Threat Bus $(date +%Y-%m-%d)"
        echo "::set-output name=name::$NAME"
    - name: GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.release_name.outputs.name }}
        draft: false
        prerelease: false
    - name: Publish to PyPI
      run: |
        python -m twine upload --verbose --non-interactive dist/*
